# line below is modified when theme is changed
import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 200

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.25
blink_interval = 500
blink_timeout = 10

[env]
TERM = "alacritty"

[font]
size = 14.0
normal = { family = "Fira Code Nerd Font", style = "Medium" }

[scrolling]
multiplier = 3

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"
